import { NextResponse } from 'next/server';
import fs from 'fs/promises';
import path from 'path';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const DOCS: Array<{ title: string; file: string }> = [
  { title: 'Production Security Checklist', file: 'deployment/PRODUCTION_SECURITY_CHECKLIST.md' },
  { title: 'Production Readiness Checklist', file: 'deployment/PRODUCTION_READINESS_CHECKLIST.md' },
  { title: 'Security Audit Report', file: 'deployment/SECURITY_AUDIT_REPORT.md' },
  { title: 'Deployment Checklist', file: 'DEPLOYMENT_CHECKLIST.md' },
];

export async function GET() {
  const generatedAt = new Date().toISOString();

  const sections: string[] = [
    '# CoreComm – Compliance Documentation Pack',
    '',
    `Generated: ${generatedAt}`,
    '',
    'This file is generated by the app and bundles the repository compliance/security docs that ship with CoreComm.',
    '',
  ];

  for (const doc of DOCS) {
    const abs = path.join(process.cwd(), doc.file);
    let body = '';
    try {
      body = await fs.readFile(abs, 'utf8');
    } catch {
      body = `> Missing file in this deployment: ${doc.file}`;
    }

    sections.push('---', '', `## ${doc.title}`, '', body.trimEnd(), '');
  }

  const content = sections.join('\n');

  return new NextResponse(content, {
    status: 200,
    headers: {
      'Content-Type': 'text/markdown; charset=utf-8',
      'Content-Disposition': 'attachment; filename="corecomm-compliance-docs.md"',
      'Cache-Control': 'no-store',
    },
  });
}
