version: '3.8'

services:
  twilio-app:
    build: .
    ports:
      - "3000:3000"
      - "443:443"  # For HTTPS
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  logs:
