import { z } from 'zod';

/**
 * Zod schema for creating a new company record.
 * This schema requires all fields that are not automatically
 * generated by the database.
 */
export const CreateCompanySchema = z.object({
  name: z.string().min(1, 'Company name is required.'),
  company_size: z.enum(['small', 'medium', 'large']),
  member_key: z.string().min(1, 'Member key is required.'),
  industry: z.string().min(1, 'Industry is required.'),
  phone_numbers: z.array(z.string()).optional(),
  business_hours: z.record(z.string(), z.string()).optional(),
  timezone: z.string().min(1, 'Timezone is required.'),
  primary_goals: z.array(z.string()).optional(),
  expected_volume: z.number().int().optional(),
  success_metrics: z.string().optional(),
  logo_url: z.string().url('Invalid URL format.').optional(),
  description: z.string().optional(),
});

/**
 * Zod schema for updating an existing company record.
 * All fields are optional because a user might only update one field at a time.
 */
export const UpdateCompanySchema = CreateCompanySchema.partial();

/**
 * Zod schema for signup form validation.
 * This validates the signup form data before creating the auth user.
 */
export const SignupSchema = z.object({
  email: z.string().email('Invalid email address.'),
  full_name: z.string().min(1, 'Full name is required.').max(100, 'Name too long'),
  phone: z.string().regex(/^\+?[\d\s\-\(\)]{10,}$/, 'Invalid phone number format').optional().or(z.literal('')),
  password: z.string()
    .min(8, 'Password must be at least 8 characters long')
    .regex(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]/, 
           'Password must contain at least one uppercase letter, one lowercase letter, one number, and one special character'),
});

/**
 * Zod schema for creating a new user profile record.
 * This is meant for a new user profile after auth.users creation.
 */
export const CreateUserProfileSchema = z.object({
  email: z.string().email('Invalid email address.'),
  full_name: z.string().min(1, 'Full name is required.'),
  phone: z.string().optional(),
});

/**
 * Zod schema for updating a user's profile.
 * All fields are optional, as a user may not update everything.
 * Key identifiers like 'id', 'email', and 'company_id' are
 * not included here as they should not be changed by the user.
 */
export const UpdateUserSchema = z.object({
  full_name: z.string().optional(),
  avatar_url: z.string().url('Invalid URL format.').optional(),
  phone: z.string().optional(),
  role: z.enum(['admin', 'member']).optional(),
  is_active: z.boolean().optional(),
});

// Call validation schemas
export const CreateCallSchema = z.object({
  caller_number: z.string().min(1, 'Caller number is required'),
  recipient_number: z.string().optional(),
  duration: z.number().int().min(0, 'Duration must be a positive integer').default(0),
  transcript: z.string().optional(),
  resolution_status: z.enum(['pending', 'resolved', 'escalated', 'failed']).default('pending'),
  call_type: z.enum(['inbound', 'outbound']).default('inbound'),
  summary: z.string().optional(),
  sentiment: z.enum(['positive', 'neutral', 'negative']).optional(),
  priority: z.enum(['low', 'medium', 'high', 'urgent']).default('medium'),
  company_id: z.string().uuid().optional(),
});

export const UpdateCallSchema = CreateCallSchema.partial();

// Query parameter schemas
export const PaginationSchema = z.object({
  page: z.coerce.number().default(1),
  limit: z.coerce.number().default(10),
});

export const CallsQuerySchema = PaginationSchema.extend({
  resolution_status: z.enum(['pending', 'resolved', 'escalated', 'failed']).optional(),
  call_type: z.enum(['inbound', 'outbound']).optional(),
  priority: z.enum(['low', 'medium', 'high', 'urgent']).optional(),
  search: z.string().optional(),
});

// ==============================================
// Vapi Assistant Validation Schemas
// ==============================================

export const ModelConfigSchema = z.object({
  provider: z.enum(['openai', 'anthropic', 'google', 'groq']),
  model: z.string().min(1, 'Model is required'),
  temperature: z.number().min(0).max(2).default(0.7),
  maxTokens: z.number().int().positive().optional(),
  knowledgeBaseId: z.string().optional(),
});

export const VoiceConfigSchema = z.object({
  provider: z.enum(['elevenlabs', 'playht', 'azure', 'deepgram']),
  voiceId: z.string().min(1, 'Voice ID is required'),
  speed: z.number().min(0.5).max(2).optional(),
  stability: z.number().min(0).max(1).optional(),
});

export const CreateAssistantSchema = z.object({
  name: z.string().min(1, 'Assistant name is required').max(100),
  description: z.string().max(500).optional(),
  systemPrompt: z.string().min(10, 'System prompt must be at least 10 characters'),
  firstMessage: z.string().min(1, 'First message is required'),
  model: ModelConfigSchema,
  voice: VoiceConfigSchema,
  knowledgeBaseId: z.string().uuid().optional(),
});

export const UpdateAssistantSchema = CreateAssistantSchema.partial();

// ==============================================
// Vapi Knowledge Base Validation Schemas
// ==============================================

export const CreateKnowledgeBaseSchema = z.object({
  name: z.string().min(1, 'Knowledge base name is required').max(100),
  description: z.string().max(500).optional(),
  provider: z.enum(['google', 'openai']).default('google'),
});

export const UpdateKnowledgeBaseSchema = CreateKnowledgeBaseSchema.partial();

// File upload validation
export const MAX_FILE_SIZE = 10 * 1024 * 1024; // 10MB hard limit
export const RECOMMENDED_FILE_SIZE = 300 * 1024; // 300KB recommended

export const ALLOWED_FILE_TYPES = [
  'text/plain',
  'application/pdf',
  'application/msword',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'text/csv',
  'text/markdown',
  'application/json',
  'application/xml',
  'text/xml',
] as const;

export const ALLOWED_FILE_EXTENSIONS = [
  '.txt', '.pdf', '.doc', '.docx', '.csv', '.md', '.json', '.xml', '.log'
] as const;

// ==============================================
// Vapi Phone Number Validation Schemas
// ==============================================

export const CreatePhoneNumberSchema = z.object({
  provider: z.enum(['vapi', 'twilio', 'vonage', 'telnyx', 'byo']).default('vapi'),
  assistantId: z.string().uuid().optional(),
  areaCode: z.string().regex(/^\d{3}$/, 'Area code must be 3 digits').optional(),
  number: z.string().optional(), // For BYO
  fallbackNumber: z.string().optional(),
});

export const UpdatePhoneNumberSchema = z.object({
  assistantId: z.string().uuid().optional().nullable(),
  isActive: z.boolean().optional(),
});

// ==============================================
// Type exports
// ==============================================

export type CreateCallInput = z.infer<typeof CreateCallSchema>;
export type UpdateCallInput = z.infer<typeof UpdateCallSchema>;
export type UpdateUserInput = z.infer<typeof UpdateUserSchema>;
export type CallsQueryInput = z.infer<typeof CallsQuerySchema>;

export type CreateAssistantInput = z.infer<typeof CreateAssistantSchema>;
export type UpdateAssistantInput = z.infer<typeof UpdateAssistantSchema>;
export type CreateKnowledgeBaseInput = z.infer<typeof CreateKnowledgeBaseSchema>;
export type UpdateKnowledgeBaseInput = z.infer<typeof UpdateKnowledgeBaseSchema>;
export type CreatePhoneNumberInput = z.infer<typeof CreatePhoneNumberSchema>;
export type UpdatePhoneNumberInput = z.infer<typeof UpdatePhoneNumberSchema>;
