import { z } from 'zod';

/**
 * Zod schema for creating a new company record.
 * This schema requires all fields that are not automatically
 * generated by the database.
 */
export const CreateCompanySchema = z.object({
  name: z.string().min(1, 'Company name is required.'),
  company_size: z.enum(['small', 'medium', 'large']),
  member_key: z.string().min(1, 'Member key is required.'),
  industry: z.string().min(1, 'Industry is required.'),
  phone_numbers: z.array(z.string()).optional(),
  business_hours: z.record(z.string(), z.string()).optional(),
  timezone: z.string().min(1, 'Timezone is required.'),
  primary_goals: z.array(z.string()).optional(),
  expected_volume: z.number().int().optional(),
  success_metrics: z.string().optional(),
  logo_url: z.string().url('Invalid URL format.').optional(),
  description: z.string().optional(),
});

/**
 * Zod schema for updating an existing company record.
 * All fields are optional because a user might only update one field at a time.
 */
export const UpdateCompanySchema = CreateCompanySchema.partial();

/**
 * Zod schema for creating a new user profile record.
 * This is meant for a new user signing up, after the auth.users
 * record has been created. It requires the 'id' from auth.users
 * and the 'company_id' for linking.
 */
export const SignupSchema = z.object({
  email: z.string().email('Invalid email address.'),
  full_name: z.string().min(1, 'Full name is required.'),
  phone: z.string().optional(),
});

/**
 * Zod schema for updating a user's profile.
 * All fields are optional, as a user may not update everything.
 * Key identifiers like 'id', 'email', and 'company_id' are
 * not included here as they should not be changed by the user.
 */
export const UpdateUserSchema = z.object({
  full_name: z.string().optional(),
  avatar_url: z.string().url('Invalid URL format.').optional(),
  phone: z.string().optional(),
  role: z.enum(['admin', 'user']).optional(),
  is_active: z.boolean().optional(),
});
